#!/usr/bin/env python3
"""Generate _extensions/pari-gp/pari-gp.xml (KDE/Skylighting syntax definition)."""

import html
import re
import subprocess
import sys

ARG_DEST = 2  # sys.argv index of the output path

CONTROL = """break next return if while until for foreach forcomposite fordiv
fordivfactored forell forfactored forpart forperm forprime forprimestep
forqfvec forsquarefree forstep forsubgroup forsubset forvec fortraverse
my local global goto""".split()

CONSTANTS = "Pi Euler Catalan I oo".split()

MEMBERS = """a1 a2 a3 a4 a6 area b2 b4 b6 b8 bid bnf c4 c6 clgp cyc diff disc e
eta f fu gen group index j mod nf no normfu omega orders p pol polabs r1 r2 reg
roots sign t2 tate tu zk zkst""".split()

DEFAULTS = """TeXstyle breakloop colors compatible datadir debug debugfiles
debugmem echo factor_add_primes factor_proven format graphcolormap
graphcolors help histfile histsize lines linewrap log logfile nbthreads
new_galois_format output parisize parisizemax path prettyprinter primelimit
prompt prompt_cont psfile readline realbitprecision realprecision recover
secure seriesprecision simplify sopath strictargs strictmatch threadsize
threadsizemax timer""".split()


def harvest(gp="gp"):
    """Ask the installed gp for its function list.

    Each help category (?1 .. ?17) is queried in its own gp invocation: when
    several ?n requests are piped into a single session gp silently drops some
    of them, which would leave whole categories (elliptic curves, ...) out of
    the keyword list.
    """
    banner = set(
        """GP PARI CALCULATOR Version released amd64 arm64 running linux
        darwin windows x86 kernel bit compiled gcc clang Ubuntu Debian threading
        engine pthread nbthreads readline disabled enabled extended help
        Copyright The Group is free software covered by the GNU General Public
        License and comes WITHOUT ANY WARRANTY WHATSOEVER Type for how to get
        moral possibly technical support quit Goodbye parisize primelimit
        factorlimit RETURN Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec GMP
        MPIR version single multi""".split()
    )
    toks = set()
    for n in [*range(1, 18), "."]:
        try:
            out = subprocess.run(
                ["sh", "-c", f"exec {gp} -f 2>&1"],
                input=f"?{n}\n",
                capture_output=True,
                text=True,
                timeout=60,
                check=False,
            ).stdout
        except subprocess.TimeoutExpired:
            continue
        for line in out.splitlines():
            for t in line.split():
                if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", t):
                    toks.add(t)
    toks -= banner
    return sorted(t for t in toks if len(t) > 1 or t == "I")


def lst(name, items):
    body = "\n".join(f"      <item>{html.escape(i)}</item>" for i in items)
    return f'    <list name="{name}">\n{body}\n    </list>'


def main():
    gp = sys.argv[1] if len(sys.argv) > 1 else "gp"
    fns = harvest(gp)
    known = set(CONTROL) | set(CONSTANTS) | set(DEFAULTS)
    fns = [f for f in fns if f not in known]
    ver = subprocess.run(
        ["sh", "-c", f"{gp} --version 2>&1"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout
    m = re.search(r"Version\s+([0-9.]+)", ver)
    pariver = m.group(1) if m else "unknown"

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<!--
  PARI/GP syntax definition for Skylighting / Pandoc / Quarto / KDE Kate.

  Generated by tools/gen_xml.py from the function list of the installed
  PARI/GP interpreter (version {pariver}). Regenerate with `make syntax`.

  PARI/GP is developed by the PARI Group, Universite de Bordeaux:
  https://pari.math.u-bordeaux.fr/
-->
<language name="pari-gp"
          alternativeNames="gp;PARI/GP;pari"
          section="Scientific"
          version="1"
          kateversion="5.0"
          extensions="*.gp;*.gpi"
          mimetype="text/x-pari-gp"
          author="Enrique Pérez Herrero"
          license="MIT"
          priority="5"
          indenter="cstyle">
  <highlighting>
{lst("controlflow", CONTROL)}
{lst("constants", CONSTANTS)}
{lst("functions", fns)}
{lst("defaults", DEFAULTS)}
{lst("members", MEMBERS)}
    <contexts>
      <context name="Normal" attribute="Normal Text" lineEndContext="#stay">
        <!-- comments: \\\\ to end of line, and C-style block comments -->
        <Detect2Chars char="\\" char1="\\" attribute="Comment" context="LineComment"/>
        <Detect2Chars char="/" char1="*" attribute="Comment" context="BlockComment" beginRegion="Comment"/>
        <!-- gp metacommands, only meaningful at the start of a line -->
        <RegExpr String="^\\s*\\\\[a-zA-Z]+" attribute="Metacommand" context="#stay" column="0"/>
        <RegExpr String="^\\s*\\\\[0-9]*\\s*$" attribute="Metacommand" context="#stay" column="0"/>
        <RegExpr String="^\\s*\\?+[a-zA-Z0-9_.*]*" attribute="Metacommand" context="#stay" column="0"/>
        <!-- strings -->
        <DetectChar char="&quot;" attribute="String" context="String"/>
        <!-- member access: E.disc, bnf.clgp ... -->
        <RegExpr String="\\.[a-zA-Z_][a-zA-Z0-9_]*" attribute="Member" context="#stay"/>
        <!-- numbers: 1.5e10, 0x1f, 3.14, 42 -->
        <RegExpr String="\\b0[xX][0-9a-fA-F]+\\b" attribute="Hex"/>
        <RegExpr String="\\b[0-9]+\\.[0-9]*([eE][-+]?[0-9]+)?" attribute="Float"/>
        <RegExpr String="\\.[0-9]+([eE][-+]?[0-9]+)?" attribute="Float"/>
        <RegExpr String="\\b[0-9]+[eE][-+]?[0-9]+" attribute="Float"/>
        <RegExpr String="\\b[0-9]+\\b" attribute="Number"/>
        <!-- keywords -->
        <keyword String="controlflow" attribute="Control Flow"/>
        <keyword String="constants" attribute="Constant"/>
        <keyword String="defaults" attribute="Default"/>
        <keyword String="functions" attribute="Function"/>
        <!-- user function definition: name(args) = -->
        <RegExpr String="\\b[a-zA-Z_][a-zA-Z0-9_]*(?=\\s*\\()" attribute="Normal Text"/>
        <!-- operators -->
        <RegExpr String="(\\+\\+|--|&lt;&lt;=?|&gt;&gt;=?|&lt;=|&gt;=|==|!=|&amp;&amp;|\\|\\||-&gt;|\\+=|-=|\\*=|/=|%=|\\\\=|\\^=)" attribute="Operator"/>
        <AnyChar String="+-*/%^!&lt;&gt;=&amp;|~?:" attribute="Operator"/>
        <AnyChar String="()[]{{}}" attribute="Symbol"/>
        <AnyChar String=",;" attribute="Symbol"/>
      </context>

      <context name="LineComment" attribute="Comment" lineEndContext="#pop"/>

      <context name="BlockComment" attribute="Comment" lineEndContext="#stay">
        <Detect2Chars char="*" char1="/" attribute="Comment" context="#pop" endRegion="Comment"/>
      </context>

      <context name="String" attribute="String" lineEndContext="#pop">
        <RegExpr String="\\\\[\\\\&quot;nt]" attribute="String Char"/>
        <DetectChar char="&quot;" attribute="String" context="#pop"/>
      </context>
    </contexts>

    <itemDatas>
      <itemData name="Normal Text"  defStyleNum="dsNormal"/>
      <itemData name="Control Flow" defStyleNum="dsControlFlow" bold="1"/>
      <itemData name="Function"     defStyleNum="dsFunction"/>
      <itemData name="Constant"     defStyleNum="dsConstant"/>
      <itemData name="Default"      defStyleNum="dsVariable"/>
      <itemData name="Member"       defStyleNum="dsAttribute"/>
      <itemData name="Metacommand"  defStyleNum="dsPreprocessor"/>
      <itemData name="Number"       defStyleNum="dsDecVal"/>
      <itemData name="Hex"          defStyleNum="dsBaseN"/>
      <itemData name="Float"        defStyleNum="dsFloat"/>
      <itemData name="String"       defStyleNum="dsString"/>
      <itemData name="String Char"  defStyleNum="dsSpecialChar"/>
      <itemData name="Comment"      defStyleNum="dsComment"/>
      <itemData name="Operator"     defStyleNum="dsOperator"/>
      <itemData name="Symbol"       defStyleNum="dsNormal"/>
    </itemDatas>
  </highlighting>

  <general>
    <comments>
      <comment name="singleLine" start="\\\\"/>
      <comment name="multiLine" start="/*" end="*/" region="Comment"/>
    </comments>
    <keywords casesensitive="1" additionalDeliminator="."/>
  </general>
</language>
"""
    dest = sys.argv[2] if len(sys.argv) > ARG_DEST else "pari-gp.xml"
    with open(dest, "w") as fh:
        fh.write(xml)
    print(f"wrote {dest}  ({len(fns)} functions, PARI/GP {pariver})")


if __name__ == "__main__":
    main()
